# Generated by Django 4.2.10 on 2024-02-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="categories",
            field=models.ManyToManyField(null=True, to="tiles.category"),
        ),
        migrations.AddField(
            model_name="series",
            name="tags",
            field=models.ManyToManyField(null=True, to="tiles.tag"),
        ),
    ]
