# Generated by Django 4.2.10 on 2024-03-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiles", "0002_series_categories_series_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="address",
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="tiles.category"),
        ),
        migrations.AlterField(
            model_name="item",
            name="series",
            field=models.ManyToManyField(blank=True, null=True, to="tiles.series"),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="tiles.tag"),
        ),
        migrations.AlterField(
            model_name="series",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="series", to="tiles.category"
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="series", to="tiles.tag"
            ),
        ),
    ]
